server:
  port: 8086
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: COMPONENT-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: COMPONENT-CLIENT-1
          uri: lb://COMPONENT-CLIENT-1
          predicates:
            - Path=/components_one/**
        - id: COMPONENT-CLIENT-2
          uri: lb://COMPONENT-CLIENT-2
          predicates:
            - Path=/components_two/**
        - id: COMPONENT-CLIENT-3
          uri: lb://COMPONENT-CLIENT-3
          predicates:
            - Path=/components_three/**